# Generated by Django 2.0.2 on 2018-03-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='party',
            field=models.CharField(max_length=255),
        ),
    ]
