# Generated by Django 2.0.2 on 2018-02-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_auctionend'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='address',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
