# Generated by Django 2.0.2 on 2018-02-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180226_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
